<?php
require_once 'config/database.php';

// Fetch all teams for display
$teams = [];
$teamResult = $pdo->query("SELECT * FROM teams ORDER BY nom ASC");
// For each team, fetch associated members (creates nested structure)
while ($team = $teamResult->fetch()) {
    $sql = "SELECT u.id_user, u.nom, u.prenom, u.grade "
      . "FROM users u "
      . "JOIN team_members tm ON u.id_user = tm.usr_id "
      . "WHERE tm.team_id = ? "
      . "ORDER BY u.nom";

    $stmt = $pdo->prepare($sql);
    $stmt->execute([$team['id_team']]);
    $team['members'] = $stmt->fetchAll(); // Nest members inside team
    $teams[] = $team;
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="assets/css/style.css" />
    <title>Laboratory Teams</title>
</head>
<body>
    <header>
      <h1>Bienvenue</h1>
      <div class="diapo-div">
        <div class="diapo">
          <img src="assets/images/image1.png" />
          <div class="separator"></div>
          <img src="assets/images/image2.png" />
          <div class="separator"></div>
          <img src="assets/images/image3.png" />
          <div class="separator"></div>
          <img src="assets/images/image4.png" />
          <div class="separator"></div>
          <img src="assets/images/image1.png" />
        </div>
      </div>
    </header>
    <nav class="mainNavBar">
      <ul class="mainNavList">
        <li><a href="#">Home</a></li>
        <li>
          <a href="#">Teams</a>
          <ul>
            <li><a href="#">Team 1</a></li>
            <li><a href="#">Team 2</a></li>
            <li><a href="#">Team 3</a></li>
          </ul>
        </li>
        <li>
          <a href="#">Publications</a>
          <ul>
            <li><a href="#">Journals</a></li>
            <li><a href="#">Conferences</a></li>
          </ul>
        </li>
        <li>
          <a href="#">Partners</a>
          <ul>
            <li><a href="#">National</a></li>
            <li><a href="#">International</a></li>
            <li><a href="#">Industry</a></li>
          </ul>
        </li>
        <li><a href="#">Contact</a></li>
      </ul>
    </nav>

    <!-- Search and Sort Controls -->
    <div class="table-controls">
        <div class="search-controls">
            <h3>Search Filters:</h3>
            <div class="search-group">
              <label for="searchTeam">Team:</label>
              <input type="text" id="searchTeam" placeholder="Search by team..." />
            </div>
            <div class="search-group">
              <label for="searchMember">Member:</label>
              <input type="text" id="searchMember" placeholder="Search by member..." />
            </div>
            <div class="search-group">
              <label for="searchStatus">Status:</label>
              <input type="text" id="searchStatus" placeholder="Search by status..." />
            </div>
            <button id="searchButton">Search</button>
        </div>
        <div class="sort-controls">
            <h3>Sort By:</h3>
            <div class="sort-group">
              <label for="sortColumn">Column:</label>
              <select id="sortColumn">
                <option value="team">Team</option>
                <option value="member">Member</option>
                <option value="status">Status</option>
              </select>
            </div>
            <div class="sort-group">
              <label for="sortOrder">Order:</label>
              <select id="sortOrder">
                <option value="asc">Ascending (A-Z)</option>
                <option value="desc">Descending (Z-A)</option>
              </select>
            </div>
            <button id="sortButton">Sort</button>
            <button id="resetButton">Reset Table</button>
        </div>
        
    </div>
    <div class="auto-refresh-indicator" style="text-align: left; padding: 10px; font-size: 12px; color: #666;">
            <span id="refreshStatus">🔄 Auto-refresh enabled (every 5 seconds)</span>
    </div>
    <table id="teamsTable" border="1">
      <thead>
        <tr>
          <th scope="col">Teams</th>
          <th scope="col">Members</th>
          <th scope="col">Status</th>
        </tr>
      </thead>
      <tbody>
    <?php foreach ($teams as $team): ?>
        <?php foreach ($team['members'] as $member): ?>
            <?php

            $status_display = htmlspecialchars($member['grade']);
            if ($member['id_user'] == $team['chef_id']) {
                $status_display .= " (Chef d'équipe)";
            }
            ?>
            <tr data-team="<?php echo htmlspecialchars($team['nom']); ?>" 
                data-member="<?php echo htmlspecialchars($member['prenom'] . ' ' . $member['nom']); ?>"
                data-status="<?php echo $status_display; // Use the new dynamic status string ?>">
                <!-- Table cells will be generated by script.js -->
            </tr>
        <?php endforeach; ?>
    <?php endforeach; ?>
</tbody>
    </table>

    <video src="assets/images/apsec.mp4" controls style="height: 500px"></video>
    <footer>
      <p>Contactez-nous : <a href="mailto:Laboratoire@esi.com">Laboratoire@esi.com</a></p>
    </footer>

    <script src="assets/js/jquery-3.6.0.js"></script>
    <script src="assets/js/script.js"></script>
    <script src="assets/js/index_ajax.js"></script>
</body>
</html>